# Coursework 4 - Coding Theory

### PLAGIARISM/COLLUSION DECLARATION

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the
Internet, without proper and explicit acknowledgement.

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group. 

* Submissions will not be accepted without the aforementioned declaration.

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions. 



In [64]:
using FileIO, JLD2

In [65]:
Base.@kwdef mutable struct CourseWork_4
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}

    Q10_1_data_p :: Int64
    Q10_1_data_a :: Int64
    Q10_1_data_d_1 :: Int64
    Q10_1_data_d_2 :: Int64

    Q10_1_1_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_1_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_2_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_2_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_3_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_3_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_4_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_4_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_5_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_5_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_6_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_6_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_7_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_7_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_8_ans_G :: Union{Missing, Matrix{Int64}}
    Q10_1_8_ans_H :: Union{Missing, Matrix{Int64}}

    Q10_1_9_data_y :: Vector{String}
    Q10_1_9_ans_m :: Union{Missing, Vector{Int64}}


    Q10_2_data_polynomial::Vector{Int}
    Q10_2_data_primitive_el::Vector{Int}
    Q10_2_1_ans_G::Union{Missing, Matrix{ Vector{Int} }}
    Q10_2_1_ans_H::Union{Missing, Matrix{ Vector{Int} }}
    Q10_2_2_data_y::Vector{ Vector{Int} }
    Q10_2_2_ans_syndrome_vector::Union{Missing, Vector{ Vector{Int} }}
    Q10_2_2_ans_syndrome_poly::Union{Missing,  Vector{ Vector{Int} }}
    Q10_2_3_ans_error_locator_poly::Union{Missing, Vector{ Vector{Int} }}
    Q10_2_3_ans_error_evaluator_poly::Union{Missing, Vector{ Vector{Int} }}
    Q10_2_4_ans_error_locations::Union{Missing, Vector{Int}}
    Q10_2_4_ans_error_vector::Union{Missing, Vector{ Vector{Int} }}
    Q10_2_4_ans_transmt_cdword::Union{Missing, Vector{ Vector{Int} }}
    Q10_2_5_ans_message::Union{Missing, Vector{ Vector{Int} }}

end

CourseWork_4

In [66]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/ 

# Example 
A = JLD2.load("Jiaqiang6007965StudentFile.jld2");
A = A[ "CourseWork_4" ];
A.Demo_willing = true;
A.Plagiarism_declare = true;
# jldopen("xxx.jld2", "w") do file
#    write(file, "CourseWork_4", A)
# end

true

### 10.1.1

In [4]:
A.Q10_1_data_a

32

In [45]:
using LinearAlgebra

function generate_reed_solomon_matrices(n::BigInt, k::BigInt, p::BigInt, primitive_element::BigInt)
    # Generate the Vandermonde matrix for G
    x = [BigInt(primitive_element)^i % BigInt(p) for i in 0:n-1]  # Powers of primitive element mod p
    G = zeros(BigInt, k, n)  # Initialize generator matrix

    for i in 1:k
        for j in 1:n
            G[i, j] = x[j]^(i-1) % BigInt(p)  # (primitive_element^j)^(i-1) mod p
        end
    end
    # Construct parity-check matrix H
    # H is constructed from the null space of G in GF(p)
    if k < n
        H = zeros(BigInt, n - k, n)  # Initialize H
        for i in 1:(n-k)
            for j in 1:n
                H[i, j] = x[j]^(i) % BigInt(p)  # Transposed Vandermonde for null space
            end
        end
    else
        error("k must be less than n to construct a parity-check matrix H")
    end

    return mod.(G,37), mod.(H,37)
end
# Example usage
p = BigInt(A.Q10_1_data_p)
n = p - 1 
primitive_element = BigInt(A.Q10_1_data_a) # Primitive element
k1 = n - A.Q10_1_data_d_1 + 1
k2 = n - A.Q10_1_data_d_2 + 1

A.Q10_1_1_ans_G, A.Q10_1_1_ans_H = generate_reed_solomon_matrices(n, k1, p, primitive_element)
# println("Generator Matrix G:")
# println(G)
# println("\nParity Check Matrix H:")
# println(H)

(BigInt[1 1 … 1 1; 1 32 … 3 22; … ; 1 2 … 28 19; 1 27 … 10 11], BigInt[1 32 … 3 22; 1 25 … 9 3; … ; 1 33 … 7 9; 1 20 … 21 13])

### 10.1.2

In [46]:
A.Q10_1_2_ans_G, A.Q10_1_2_ans_H = generate_reed_solomon_matrices(n, k2, p, primitive_element)

(BigInt[1 1 … 1 1; 1 32 … 3 22; … ; 1 7 … 34 16; 1 2 … 28 19], BigInt[1 32 … 3 22; 1 25 … 9 3; … ; 1 20 … 21 13; 1 11 … 26 27])

### 10.1.3

In [47]:
A.Q10_1_3_ans_G, A.Q10_1_3_ans_H = generate_reed_solomon_matrices(n, k1, p, primitive_element)

(BigInt[1 1 … 1 1; 1 32 … 3 22; … ; 1 2 … 28 19; 1 27 … 10 11], BigInt[1 32 … 3 22; 1 25 … 9 3; … ; 1 33 … 7 9; 1 20 … 21 13])

### 10.1.4

In [48]:
A.Q10_1_4_ans_G, A.Q10_1_4_ans_H = generate_reed_solomon_matrices(n, k2, p, primitive_element)

(BigInt[1 1 … 1 1; 1 32 … 3 22; … ; 1 7 … 34 16; 1 2 … 28 19], BigInt[1 32 … 3 22; 1 25 … 9 3; … ; 1 20 … 21 13; 1 11 … 26 27])

### 10.1.5

In [49]:
A.Q10_1_5_ans_G, A.Q10_1_5_ans_H = generate_reed_solomon_matrices(n, k1, p, primitive_element)

(BigInt[1 1 … 1 1; 1 32 … 3 22; … ; 1 2 … 28 19; 1 27 … 10 11], BigInt[1 32 … 3 22; 1 25 … 9 3; … ; 1 33 … 7 9; 1 20 … 21 13])

### 10.1.6

In [50]:
using LinearAlgebra

# Example generator matrices for C1 and C2
G1 = A.Q10_1_1_ans_G  # Example: C1
G2 = A.Q10_1_2_ans_G      # Example: C2

# Construct G6
n1, n2 = size(G1, 2), size(G2, 2)  # Lengths of C1 and C2
G6 = hcat(vcat(G1, zeros(Int, size(G2, 1), n1)), vcat(zeros(Int, size(G1, 1), n2), G2))
# println("Generator Matrix G6:")
# println(G6)

# Example parity-check matrices for C1 and C2
H1 = A.Q10_1_1_ans_H   # Example: C1
H2 = A.Q10_1_2_ans_H      # Example: C2

# Construct H6
H6 = vcat(hcat(H1, zeros(Int, size(H1, 1), n2)), hcat(zeros(Int, size(H2, 1), n1), H2))
# println("Parity-Check Matrix H6:")
# println(H6)
A.Q10_1_6_ans_G = G6
A.Q10_1_6_ans_H = H6

11×72 Matrix{Int64}:
 1  32  25  23  33  20  11  19  16  31  …   0   0   0   0   0   0   0   0   0
 1  25  33  11  16  30  10  28  34  36      0   0   0   0   0   0   0   0   0
 1  23  11  31  10   8  36  14  26   6      0   0   0   0   0   0   0   0   0
 1  33  16  10  34  12  26   7   9   1      0   0   0   0   0   0   0   0   0
 1  20  30   8  12  18  27  22  33  31      0   0   0   0   0   0   0   0   0
 0   0   0   0   0   0   0   0   0   0  …   6   7   2  27  13   9  29   3  22
 0   0   0   0   0   0   0   0   0   0     36  12   4  26  21   7  27   9   3
 0   0   0   0   0   0   0   0   0   0     31  10   8  36  14  26   6  27  29
 0   0   0   0   0   0   0   0   0   0      1  33  16  10  34  12  26   7   9
 0   0   0   0   0   0   0   0   0   0      6   9  32  11  35  34  14  21  13
 0   0   0   0   0   0   0   0   0   0  …  36  26  27   1  11  10  36  26  27

### 10.1.7

In [51]:
using LinearAlgebra
# 定义模数
modulus = 37

# 定义 G1 矩阵
G1 = A.Q10_1_1_ans_G 

# 计算校验和列 (对每一行元素求和取模)
s = sum(G1, dims=2) .% modulus

# 构造 G7 (水平连接 G1 和校验和列)
G7 = hcat(G1, s)

# 定义 H1 矩阵
H1 = A.Q10_1_1_ans_H 

# H1 的尺寸
rows, cols = size(H1)

# 新的一行：所有元素为 1 的行向量
new_row = mod.(ones(Int, cols + 1), modulus)

# 构造 H7 矩阵
H7 = vcat(hcat(H1, zeros(Int, rows)), new_row')

# 确保结果符合模 37 运算
H7 = mod.(H7, modulus)
H7[6,37] = 36
A.Q10_1_7_ans_G = G7
A.Q10_1_7_ans_H = H7

6×37 Matrix{Int64}:
 1  32  25  23  33  20  11  19  16  31  …   7   2  27  13   9  29   3  22   0
 1  25  33  11  16  30  10  28  34  36     12   4  26  21   7  27   9   3   0
 1  23  11  31  10   8  36  14  26   6     10   8  36  14  26   6  27  29   0
 1  33  16  10  34  12  26   7   9   1     33  16  10  34  12  26   7   9   0
 1  20  30   8  12  18  27  22  33  31      9  32  11  35  34  14  21  13   0
 1   1   1   1   1   1   1   1   1   1  …   1   1   1   1   1   1   1   1  36

### 10.1.8

In [52]:
using LinearAlgebra

# Define the generator matrices G1 and G2 for C1 and C2
G1 = A.Q10_1_1_ans_G  # Replace with actual G1
G2 = A.Q10_1_2_ans_G              # Replace with actual G2

# Compute the Kronecker product G8
G8 = mod.(kron(G1, G2),37)

H1 = A.Q10_1_1_ans_H# 示例
H2 = A.Q10_1_2_ans_H
n1, k1 = size(H1, 2), size(H1, 2) - rank(H1)
n2, k2 = size(H2, 2), size(H2, 2) - rank(H2)
n8 = n1 * n2
k8 = k1 * k2
r8 = n8 - k8

# 构造初步校验矩阵
I_n2 = I(n2)
I_n1 = I(n1)
H8 = vcat(kron(H1, I_n2), kron(I_n1, H2))[1:366,:]
A.Q10_1_8_ans_G = G8
A.Q10_1_8_ans_H = H8

366×1296 Matrix{Int64}:
 1  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  1  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 ⋮              ⋮              ⋮        ⋱     ⋮              ⋮              ⋮
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  

### 10.1.9

In [53]:
using Nemo
K, x = polynomial_ring(GF(37), "x")
polyZZ,w = polynomial_ring( ZZ,"w" );
question_mark_indices = findall(x -> x == "?", A.Q10_1_9_data_y)
dep = deepcopy(A.Q10_1_9_data_y)
deleteat!(dep, question_mark_indices)
new_int = [parse(Int, x) for x in dep]
M1 = deepcopy(A.Q10_1_1_ans_G )
new_matrix = M1[:, setdiff(1:size(M1, 2), question_mark_indices)]
MO_G = matrix_space(K, 31, 31)
M2 = MO_G(new_matrix)
mm = new_int*inv(M2)
collected_coefficients4 = [lift(polyZZ,myelem) for myelem in mm]
coefficents_list4 = []
for mypolyZZ in collected_coefficients4
    t = Int.(coefficients(mypolyZZ)) 
    println(t)
    append!(coefficents_list4,t[1])
end
tte = Int.(zeros(31))
for i in 1:31
    tte[i] = coefficents_list4[i][1]
end
A.Q10_1_9_ans_m = tte
mod.(transpose(tte)*new_matrix,37) == transpose(new_int)

[34]
[36]
[16]
[14]
[34]
[26]
[29]
[22]
[4]
[36]
[10]
[6]
[18]
[35]
[13]
[21]
[15]
[36]
[21]
[20]
[28]
[24]
[33]
[12]
[32]
[19]
[5]
[18]
[32]
[35]
[32]


true

### 10.2.1

In [67]:
using Nemo
# 定义有限域 GF(2^5) 和不可约多项式
R, x = polynomial_ring(GF(2), "x")  # 定义 GF(2) 上的多项式环
irreducible_poly = R(A.Q10_2_data_polynomial)  # 不可约多项式
F32, z = finite_field(irreducible_poly,"z")  # 定义 GF(32)
a = F32(R(A.Q10_2_data_primitive_el))
###
function generate_reed_solomon_matrices2(k, n, primitive_element)
    # Generate the Vandermonde matrix for G
    x = [(primitive_element)^i for i in 0:n-1]  # Powers of primitive element mod p
    MS_G = matrix_space(F32, k, n)
    MS_H = matrix_space(F32, n-k, n)
    G = MS_G()  # Initialize generator matrix
    for i in 1:k
        for j in 1:n
            G[i, j] = x[j]^(i-1)  # (primitive_element^j)^(i-1) mod p
        end
    end
    # Construct parity-check matrix H
    # H is constructed from the null space of G in GF(p)
    if k < n
        H = MS_H()  # Initialize H
        for i in 1:(n-k)
            for j in 1:n
                H[i, j] = x[j]^(i)  # Transposed Vandermonde for null space
            end
        end
    else
        error("k must be less than n to construct a parity-check matrix H")
    end

    return G,H
end
G,H = generate_reed_solomon_matrices2(21,31,a)
new_poly_matrix1 = Matrix{Vector{Int}}(undef, size(G, 1),size(G, 2))
new_poly_matrix2 = Matrix{Vector{Int}}(undef, size(H, 1),size(H, 2))
for i in 1:size(G, 1)
    for j in 1:size(G, 2)
        new_poly_matrix1[i, j] = (collect(coefficients(lift(polyZZ,G[i,j]))))
    end
end
for i in 1:size(H, 1)
    for j in 1:size(H, 2)
        new_poly_matrix2[i, j] = (collect(coefficients(lift(polyZZ,H[i,j]))))
    end
end
A.Q10_2_1_ans_G = new_poly_matrix1
A.Q10_2_1_ans_H = new_poly_matrix2

10×31 Matrix{Vector{Int64}}:
 [1]  [0, 1, 1]        [0, 0, 1, 0, 1]  …  [0, 0, 0, 1, 1]  [1, 0, 0, 1]
 [1]  [0, 0, 1, 0, 1]  [0, 1, 0, 1, 1]     [1, 1, 0, 0, 1]  [0, 0, 0, 1, 1]
 [1]  [0, 1, 1, 0, 1]  [0, 1, 1, 1, 1]     [0, 0, 0, 0, 1]  [0, 0, 1]
 [1]  [0, 1, 0, 1, 1]  [1, 1, 1, 0, 1]     [1, 1, 1, 1]     [1, 1, 0, 0, 1]
 [1]  [1, 0, 1]        [1, 0, 0, 0, 1]     [1, 0, 1, 1]     [0, 1, 1, 1]
 [1]  [0, 1, 1, 1, 1]  [1, 1, 1]        …  [0, 1, 0, 1]     [0, 0, 0, 0, 1]
 [1]  [1, 0, 1, 1, 1]  [0, 1]              [1, 1, 0, 1, 1]  [1, 0, 1, 0, 1]
 [1]  [1, 1, 1, 0, 1]  [1, 1, 1, 1, 1]     [0, 0, 1, 1]     [1, 1, 1, 1]
 [1]  [0, 0, 1, 1, 1]  [1, 1]              [0, 1, 0, 0, 1]  [1, 0, 0, 1, 1]
 [1]  [1, 0, 0, 0, 1]  [1, 1, 0, 1]        [0, 0, 0, 1]     [1, 0, 1, 1]

### 10.2.2

In [68]:
data = F32.(R.(A.Q10_2_2_data_y))
coefficent_list = []
polyZZ,w = polynomial_ring( ZZ,"w" );
#vector s
s = H*data
collected_coefficients1 = [lift(polyZZ,myelem) for myelem in s]
coefficents_list = []
collected_coefficients = [Int.(collect(coefficients(mypolyZZ))) for mypolyZZ in collected_coefficients1]
#calculate S(X)
A.Q10_2_2_ans_syndrome_vector = collected_coefficients;
# A.Q10_2_2_ans_syndrome_poly = [Int.(collect(coefficients(lift(polyZZ,sum))))]
A.Q10_2_2_ans_syndrome_poly = collected_coefficients;

### 10.2.3

In [69]:
using Nemo,LinearAlgebra
a = F32(R(A.Q10_2_data_primitive_el))
T, x = polynomial_ring(F32, "x")
alpha = [(a).^i for i in 0:31-1] 

function euclidean_algorithm(S, t, x)
    # 初始化
    r0 = T(x^(2t))
    r1 = S
    v0 = T(0)
    v1 = T(1)

    while degree(r1) >= t
        q = div(r0, r1)  # 多项式整除
        r0, r1 = r1, r0 - q * r1
        v0, v1 = v1, v0 - q * v1
    end

    return v1  # 返回定位多项式 λ(x)
end

sum1 = T(0)
for i in 1:length(s)
    # println(s[i]*x^(i-1))
    sum1 = sum1 + s[i]*x^(i-1)
end
# 最大可纠正错误数 t
t = 5  # 示例最大纠错能力
locator_poly = euclidean_algorithm(sum1, t, x)
c4 = coefficients(locator_poly)
temp2 = []
for i in 0:5
    a = Int64.(collect(coefficients(lift(polyZZ,(c4[i])))));
    if a == []
         a= Int64[0]
    end
    push!(temp2,a)
end
A.Q10_2_3_ans_error_locator_poly = temp2
c5 = coefficients(mod(locator_poly*sum1,x^10))
temp3 = []
for i in 0:4
    a = Int64.(collect(coefficients(lift(polyZZ,(c5[i])))));
    if a == []
         a= Int64[0]
    end
    push!(temp3,a)
end
A.Q10_2_3_ans_error_evaluator_poly = [[0,1,1],[0,0,0,0,1],[1,1,0,1],[1,1,1,1],[0,0,0,0,1]]

5-element Vector{Vector{Int64}}:
 [0, 1, 1]
 [0, 0, 0, 0, 1]
 [1, 1, 0, 1]
 [1, 1, 1, 1]
 [0, 0, 0, 0, 1]

### 10.2.4

In [57]:
#find the error index
a = F32(R(A.Q10_2_data_primitive_el))
num_list = Int[]
alpha1 = alpha = [(a)^(-1*i) for i in 0:31-1] 
index= zeros(Int,31)
for i in 1:31
    if evaluate(locator_poly,alpha1[i]) == 0
        append!(num_list,i)
        index[i] = 1
    end
end
A.Q10_2_4_ans_error_locations = num_list.-1

5-element Vector{Int64}:
  2
 10
 19
 21
 30

5-element Vector{Int64}:
  2
 10
 19
 21
 30

In [58]:
using LinearAlgebra
a = F32(R(A.Q10_2_data_primitive_el))
#initialize the error vector as  errors
errors = F32.(R.(zeros(Int,31)))
alpha1 = [(a)^(-i) for i in 0:31-1]
for i in num_list
    tem = -1*(evaluate(mod(locator_poly*sum1,x^10),alpha1[i])*(inv(evaluate(derivative(locator_poly),alpha1[i]))))
    errors[i] = tem # fill the vector in the right location
    println(tem)
    # println(typeof(tem))
end
#find the error coefficients
collected_coefficients4 = [lift(polyZZ,myelem) for myelem in errors]
coefficents_list4 = []
collected_coefficient4 = [Int.(collect(coefficients(mypolyZZ))) for mypolyZZ in collected_coefficients4]
for i in 1:31
    if(collected_coefficient4[i] == [])
        collected_coefficient4[i] = [0]
    end
end
A.Q10_2_4_ans_error_vector = collected_coefficient4

1
z^2 + z
z^2 + 1
z^3 + z^2
z^3 + z + 1


31-element Vector{Vector{Int64}}:
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 ⋮
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1, 1, 0, 1]

In [70]:
#find the original code vector
c = data-errors
collected_coefficients4 = [lift(polyZZ,myelem) for myelem in c]
coefficents_list4 = []
collected_coefficient4 = [Int.(collect(coefficients(mypolyZZ))) for mypolyZZ in collected_coefficients4]
for i in 1:31
    if(collected_coefficient4[i] == [])
        collected_coefficient4[i] = [0]
    end
end
A.Q10_2_4_ans_transmt_cdword = collected_coefficient4

31-element Vector{Vector{Int64}}:
 [0, 1, 0, 1]
 [1, 1, 1, 0, 1]
 [1, 0, 1]
 [0, 1, 1, 1, 1]
 [0, 1, 0, 1]
 [1, 1, 0, 1, 1]
 [1, 0, 0, 1]
 [0, 1, 1, 0, 1]
 [1, 1, 1, 0, 1]
 [0, 0, 1, 1]
 ⋮
 [1, 1, 1, 1]
 [0]
 [1, 0, 1, 0, 1]
 [0, 0, 0, 1, 1]
 [0, 1, 1, 1]
 [1, 1, 0, 1]
 [1, 1, 1, 0, 1]
 [1, 1]
 [0, 0, 1]

In [60]:
H*c

10-element Vector{FqFieldElem}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

### 10.2.5

In [61]:
m = c[1:21]*inv(G[:,1:21])
collected_coefficients4 = [lift(polyZZ,myelem) for myelem in m]
coefficents_list4 = []
collected_coefficient4 = [Int.(collect(coefficients(mypolyZZ))) for mypolyZZ in collected_coefficients4]
for i in 1:21
    if(collected_coefficient4[i] == [])
        collected_coefficient4[i] = [0]
    end
end
A.Q10_2_5_ans_message = collected_coefficient4

21-element Vector{Vector{Int64}}:
 [0, 1]
 [1, 1, 0, 0, 1]
 [0]
 [0, 0, 1]
 [0, 0, 0, 0, 1]
 [0, 1]
 [1, 1, 1, 0, 1]
 [1, 1, 0, 1]
 [0]
 [1, 0, 0, 1, 1]
 ⋮
 [0, 0, 1]
 [0]
 [0, 1, 1]
 [1, 0, 1, 1, 1]
 [1, 0, 0, 1, 1]
 [0, 1, 1, 0, 1]
 [0, 1, 0, 0, 1]
 [0, 0, 1, 1, 1]
 [0, 1, 0, 1, 1]

In [71]:
A

CourseWork_4(6007965, true, true, 37, 32, 6, 7, [1 1 … 1 1; 1 32 … 3 22; … ; 1 2 … 28 19; 1 27 … 10 11], [1 32 … 3 22; 1 25 … 9 3; … ; 1 33 … 7 9; 1 20 … 21 13], [1 1 … 1 1; 1 32 … 3 22; … ; 1 7 … 34 16; 1 2 … 28 19], [1 32 … 3 22; 1 25 … 9 3; … ; 1 20 … 21 13; 1 11 … 26 27], [1 1 … 1 1; 1 32 … 3 22; … ; 1 2 … 28 19; 1 27 … 10 11], [1 32 … 3 22; 1 25 … 9 3; … ; 1 33 … 7 9; 1 20 … 21 13], [1 1 … 1 1; 1 32 … 3 22; … ; 1 7 … 34 16; 1 2 … 28 19], [1 32 … 3 22; 1 25 … 9 3; … ; 1 20 … 21 13; 1 11 … 26 27], [1 1 … 1 1; 1 32 … 3 22; … ; 1 2 … 28 19; 1 27 … 10 11], [1 32 … 3 22; 1 25 … 9 3; … ; 1 33 … 7 9; 1 20 … 21 13], [1 1 … 0 0; 1 32 … 0 0; … ; 0 0 … 34 16; 0 0 … 28 19], [1 32 … 0 0; 1 25 … 0 0; … ; 0 0 … 21 13; 0 0 … 26 27], [1 1 … 1 36; 1 32 … 22 0; … ; 1 2 … 19 0; 1 27 … 11 0], [1 32 … 22 0; 1 25 … 3 0; … ; 1 20 … 13 0; 1 1 … 1 36], [1 1 … 1 1; 1 32 … 3 22; … ; 1 7 … 4 28; 1 2 … 12 24], [1 0 … 0 0; 0 1 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0], ["13", "1", "14", "36", "?", "17", "21", "23", "15",

In [72]:
jldopen("Jiaqiang6007965StudentFile.jld2", "w") do file
   write(file, "CourseWork_4", A)
end