# Coursework 3 - Coding Theory

### PLAGIARISM/COLLUSION DECLARATION

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the
Internet, without proper and explicit acknowledgement.

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group. 

* Submissions will not be accepted without the aforementioned declaration.

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions. 



In [1]:
using FileIO, JLD2

In [2]:
Base.@kwdef mutable struct CourseWork_3
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}
    

    "Chapter 8"
    # Q8.1
    Q8_1_a_data_p::Int
    Q8_1_a_data_d::Int
    Q8_1_a_ans_polys::Union{Missing, Vector{Vector{Int}}}

    Q8_1_b_data_p::Int
    Q8_1_b_data_d::Int
    Q8_1_b_ans_polys::Union{Missing, Vector{Vector{Int}}}

    # Q8.2
    Q8_2_data_coeffs::Vector{Int}
    Q8_2_a_ans_is_irreducible::Union{Missing,Bool}
    Q8_2_b_ans_is_irreducible::Union{Missing,Bool}
    Q8_2_c_ans_is_irreducible::Union{Missing,Bool}
 
    # Q8.3
    Q8_3_a_data_m::Vector{Int}
    Q8_3_a_data_a::Vector{Int}
    Q8_3_a_data_b::Vector{Int}
    Q8_3_a_ans_p::Union{Missing, Vector{Vector{Int}}} # remind template form[[]]
 
    Q8_3_b_data_m::Vector{Int}
    Q8_3_b_data_a::Vector{Int}
    Q8_3_b_data_b::Vector{Int}
    Q8_3_b_ans_p::Union{Missing, Vector{Vector{Int}}}
 
    Q8_3_c_data_m::Vector{Int}
    Q8_3_c_data_a::Vector{Int}
    Q8_3_c_data_b::Vector{Int}
    Q8_3_c_ans_p::Union{Missing, Vector{Vector{Int}}}

    # Q8.4
    Q8_4_a_data_f1::Vector{Int}
    Q8_4_a_ans::Union{Missing, Vector{Vector{Int}}}

    Q8_4_b_data_f2::Vector{Int}
    Q8_4_b_ans::Union{Missing, Vector{Vector{Int}}}

    # Q8.5
    Q8_5_data_f1::Vector{Int}
    Q8_5_data_f2::Vector{Int}
    Q8_5_data_p1::Vector{Int}
    Q8_5_data_p2::Vector{Int}
    Q8_5_data_p3::Vector{Int}
    Q8_5_a_data_g1::Vector{Int}
    Q8_5_b_data_g2::Vector{Int}

    Q8_5_a_ans_q1::Union{Missing, Vector{Int}}
    Q8_5_a_ans_q2::Union{Missing, Vector{Int}}
    Q8_5_a_ans_q3::Union{Missing, Vector{Int}}
    Q8_5_a_ans_q4::Union{Missing, Vector{Int}}
    Q8_5_a_ans_q5::Union{Missing, Vector{Int}}

    Q8_5_b_ans_q1::Union{Missing, Vector{Int}}
    Q8_5_b_ans_q2::Union{Missing, Vector{Int}}
    Q8_5_b_ans_q3::Union{Missing, Vector{Int}}
    Q8_5_b_ans_q4::Union{Missing, Vector{Int}}
    Q8_5_b_ans_q5::Union{Missing, Vector{Int}}

    # Q9.1
    Q9_1_data_r :: Int64
    Q9_1_a_ans_H :: Union{Missing, Matrix{Int64}}

    Q9_1_b_ans_G :: Union{Missing, Matrix{Int64}}

    Q9_1_c_data_p :: Float64
    Q9_1_c_ans_p_err :: Union{Missing, Float64}

    Q9_1_d_data_y_1 :: Vector{String}
    Q9_1_d_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_iii :: Union{Missing, Vector{Int64}}

    Q9_1_e_data_p :: Float64
    Q9_1_e_ans_p_err :: Union{Missing, Float64}

    Q9_1_f_data_y_2 :: Vector{String}
    Q9_1_f_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_f_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_f_ans_iii :: Union{Missing, Vector{Int64}}

    # "Q9.2"
    Q9_2_data_r :: Int64
    Q9_2_data_q :: Int64

    Q9_2_a_ans_H :: Union{Missing, Matrix{Int64}}

    Q9_2_b_ans_G :: Union{Missing, Matrix{Int64}}

    Q9_2_c_data_p :: Float64
    Q9_2_c_ans_p_err :: Union{Missing, Float64}

    Q9_2_d_data_y_1 :: Vector{String}
    Q9_2_d_ans_i :: Union{Missing, Vector{Int64}}
    Q9_2_d_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_2_d_ans_iii :: Union{Missing, Vector{Int64}}

    Q9_2_e_data_p :: Float64
    Q9_2_e_ans_p_err :: Union{Missing, Float64}

    Q9_2_f_data_y_2 :: Vector{String}
    Q9_2_f_ans_i :: Union{Missing, Vector{Int64}}
    Q9_2_f_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_2_f_ans_iii :: Union{Missing, Vector{Int64}}

end

CourseWork_3

In [3]:
# Download and upload data from JLD file, refer to https://juliaio.github.io/JLD2.jl/dev/ 
A = JLD2.load("Jiaqiang6007965StudentFile.jld2");
A = A[ "CourseWork_3" ];
A.Demo_willing = true;
A.Plagiarism_declare = true;
# jldopen("xxx.jld2", "w") do file
#    write(file, "CourseWork_3", A)
# end

true

### 8.1

In [287]:
function generate_coeff_vectors(p, d)
    max_value = p^(d + 1) - 1  
    vectors = []

    for i in 0:max_value
        coeffs = digits(i; base=p)  
        # while length(coeffs) <= d   
        #     push!(coeffs, 0);
        # end
        push!(vectors, coeffs);
    end

    return vectors;
end
A.Q8_1_a_ans_polys = generate_coeff_vectors(A.Q8_1_a_data_p, A.Q8_1_a_data_d);

function generate_coeff_vectors1(p, d)
    max_value = p^(d + 1) - 1  # Maximum value of coefficient vector
    vectors = []

    for i in 0:max_value
        coeffs = digits(i; base=p)  
        # while length(coeffs) <= d   `
        #     push!(coeffs, 0);
        # end
        if length(coeffs) == d + 1
            push!(vectors, coeffs);
        end
    end
    return vectors;
end

A.Q8_1_b_ans_polys = generate_coeff_vectors1(A.Q8_1_b_data_p, A.Q8_1_b_data_d)
# use p = 2 and d = 5 to test
# result = generate_coeff_vectors(2, 5)
# for vec in result
#     println(vec)
# end


162-element Vector{Any}:
 [0, 0, 0, 0, 1]
 [1, 0, 0, 0, 1]
 [2, 0, 0, 0, 1]
 [0, 1, 0, 0, 1]
 [1, 1, 0, 0, 1]
 [2, 1, 0, 0, 1]
 [0, 2, 0, 0, 1]
 [1, 2, 0, 0, 1]
 [2, 2, 0, 0, 1]
 [0, 0, 1, 0, 1]
 ⋮
 [0, 0, 2, 2, 2]
 [1, 0, 2, 2, 2]
 [2, 0, 2, 2, 2]
 [0, 1, 2, 2, 2]
 [1, 1, 2, 2, 2]
 [2, 1, 2, 2, 2]
 [0, 2, 2, 2, 2]
 [1, 2, 2, 2, 2]
 [2, 2, 2, 2, 2]

### 8.2

In [288]:
using Nemo

function IS_irreducible(coeffs, p)
    # create polunomial ring
    R, x = polynomial_ring(GF(p), "x")
    
    poly = R(coeffs)
    
    # Check if a polynomial is irreducible
    return is_irreducible(poly)
end

coeffs = A.Q8_2_data_coeffs
A.Q8_2_a_ans_is_irreducible = IS_irreducible(coeffs, 2);
A.Q8_2_b_ans_is_irreducible = IS_irreducible(coeffs, 3);
A.Q8_2_c_ans_is_irreducible = IS_irreducible(coeffs, 5);
# println(IS_irreducible(coeffs, 2))
# println(IS_irreducible(coeffs, 3))
# println(IS_irreducible(coeffs, 5))


false

### 8.3
##### Please make sure your answer is exactly the type as defined. For example, if your answer is empty, save it as [[ ]].

In [ ]:
using Nemo

# Define finite field F_3
R, x = polynomial_ring(GF(3), "x")

# define polynomial a(x), b(x), m(x)
a = R(A.Q8_3_a_data_a)  
b = R(A.Q8_3_a_data_b) 
m = R(A.Q8_3_a_data_m)  

# Find the solution that satisfies the conditions p(x)
solutions = []
degree_limit = degree(m) - 1

# Iterate over all possible p(x) coefficient combinations
for deg in 0:degree_limit
    coeff_range = 0:2
    coeff_combinations = Iterators.product(ntuple(_ -> coeff_range, deg + 1)...)
    for coeffs in coeff_combinations
        p_candidate = R([coeffs...]) 
        if rem(a * p_candidate, m) == rem(b, m)
            push!(solutions, collect(coeffs))  
        end
    end    
end

# save to A.Q8_3_a_ans_p
# solutions
A.Q8_3_a_ans_p = [[2,0,0,1]]

1-element Vector{Vector{Int64}}:
 [2, 0, 0, 1]

In [251]:
using Nemo

# Define finite field F_3
R, x = polynomial_ring(GF(3), "x")

a = R(A.Q8_3_b_data_a)  
b = R(A.Q8_3_b_data_b)  
m = R(A.Q8_3_b_data_m)  

solutions = []
degree_limit = degree(m) - 1

# Iterate over all possible p(x) coefficient combinations
for deg in 0:degree_limit
    coeff_range = 0:2
    coeff_combinations = Iterators.product(ntuple(_ -> coeff_range, deg + 1)...)
    for coeffs in coeff_combinations
        p_candidate = R([coeffs...])  
        if rem(a * p_candidate, m) == rem(b, m)
            push!(solutions, collect(coeffs)) 
        end
    end    
end
A.Q8_3_b_ans_p = [Int[]] 

1-element Vector{Vector{Int64}}:
 []

In [252]:
using Nemo
# Define finite field F_3
R, x = polynomial_ring(GF(3), "x")

# define polynomial a(x), b(x), m(x)
a = R(A.Q8_3_c_data_a)  
b = R(A.Q8_3_c_data_b)  
m = R(A.Q8_3_c_data_m)  

solutions = []
degree_limit = degree(m) - 1

for deg in 0:degree_limit
    coeff_range = 0:2
    coeff_combinations = Iterators.product(ntuple(_ -> coeff_range, deg + 1)...)
    for coeffs in coeff_combinations
        p_candidate = R([coeffs...])  
        if rem(a * p_candidate, m) == rem(b, m)
            push!(solutions, collect(coeffs))  
        end
    end    
end

A.Q8_3_c_ans_p = solutions 

6-element Vector{Any}:
 [0, 2]
 [0, 2, 0]
 [0, 2, 0, 0]
 [0, 2, 0, 0, 0]
 [1, 0, 1, 0, 1]
 [2, 1, 2, 0, 2]

### 8.4


In [5]:
using Nemo

# Define finite fields and polynomial rings
R, u = polynomial_ring(GF(2), "u")
mypoly = R(A.Q8_4_a_data_f1)
F, x = finite_field(mypoly , "x");
field_order = 64
# Generate all non-zero elements in a finite field
elements = [F(1)]
current = F(u)  # 从 u 开始
for i in 2:field_order-1
    push!(elements, current)
    current *= F(u)  # Multiply u each time to get the next element
end

# Function to determine primitive element
function is_primitive_element(x, field_order)
    ord = 1
    power = x
    while power != F(1)
        power *= x
        ord += 1
    end
    return ord == field_order - 1
end

# Find all primitives
primitive_elements = []
for elem in elements
    if is_primitive_element(elem, field_order)
        push!(primitive_elements, elem)
    end
end

sort!(primitive_elements, by=x -> string(x))

# # Print results
# println("all primitive_elements：")
# println(primitive_elements)

# Check if u is a primitive
is_u_primitive = is_primitive_element(F(u), field_order)
# println("Whether polynomial u is a primitive element：", is_u_primitive)
### collect that
coefficent_list = []
polyZZ,w = polynomial_ring( ZZ,"w" );
collected_coefficients = [lift(polyZZ,myelem) for myelem in primitive_elements]
coefficents_list = []
collected_coefficients = [Int.(collect(coefficients(mypolyZZ))) for mypolyZZ in collected_coefficients]
A.Q8_4_a_ans = collected_coefficients


36-element Vector{Vector{Int64}}:
 [0, 1]
 [0, 0, 1]
 [1, 1, 1]
 [1, 0, 0, 1]
 [0, 1, 0, 1]
 [1, 1, 0, 1]
 [0, 0, 1, 1]
 [1, 0, 1, 1]
 [0, 0, 0, 0, 1]
 [1, 1, 0, 0, 1]
 ⋮
 [0, 1, 0, 0, 1, 1]
 [1, 1, 1, 0, 1, 1]
 [0, 0, 0, 1, 1, 1]
 [1, 0, 0, 1, 1, 1]
 [0, 1, 0, 1, 1, 1]
 [1, 1, 0, 1, 1, 1]
 [0, 0, 1, 1, 1, 1]
 [1, 0, 1, 1, 1, 1]
 [0, 1, 1, 1, 1, 1]

In [8]:
using Nemo

# Define finite fields and polynomial rings
R, u = polynomial_ring(GF(2), "u")
mypoly = R(A.Q8_4_b_data_f2)
F, x = finite_field(mypoly , "x");
field_order = 10
# Generate all non-zero elements in a finite field
elements = [F(1)]
current = F(u)  # 从 u 开始
for i in 2:field_order-1
    push!(elements, current)
    current *= F(u)  # Multiply u each time to get the next element
end

# Function to determine primitive element
function is_primitive_element(x, field_order)
    ord = 1
    power = x
    while power != F(1)
        power *= x
        ord += 1
    end
    return ord == field_order - 1
end

# Find all primitives
primitive_elements = []
for elem in elements
    if is_primitive_element(elem, field_order)
        push!(primitive_elements, elem)
    end
end

sort!(primitive_elements, by=x -> string(x))

# # Print results
# println("all primitive_elements：")
# println(primitive_elements)

# Check if u is a primitive
is_u_primitive = is_primitive_element(F(u), field_order)
# println("Whether polynomial u is a primitive element：", is_u_primitive)
### collect that
coefficent_list = []
polyZZ,w = polynomial_ring( ZZ,"w" );
collected_coefficients = [lift(polyZZ,myelem) for myelem in primitive_elements]
coefficents_list = []
collected_coefficients = [Int.(collect(coefficients(mypolyZZ))) for mypolyZZ in collected_coefficients]
A.Q8_4_b_ans = collected_coefficients

6-element Vector{Vector{Int64}}:
 [0, 1]
 [0, 0, 1]
 [0, 0, 0, 0, 1]
 [0, 1, 0, 0, 1]
 [0, 0, 0, 0, 0, 1]
 [0, 0, 1, 0, 0, 1]

### 8.5



In [ ]:
using Nemo

# Define finite field F2
F2 = GF(2)

# Define polynomial rings
R, u = polynomial_ring(F2, "u")
S, v = polynomial_ring(F2, "v")
#Define irreducible polynomials f1(u) and f2(v)
f1 = R(A.Q8_5_data_f1)
f2 = S(A.Q8_5_data_f2)

# elements on the domain
p1 = R(A.Q8_5_data_p1)
p2 = R(A.Q8_5_data_p2)
p3 = R(A.Q8_5_data_p3)
g = S(A.Q8_5_a_data_g1)

# Define mapping φ
function φ(poly, g, mod_poly)
    mapped_poly = S(0)
    for i in 0:degree(poly)
        mapped_poly += coeff(poly, i) * (g^i)
    end
    return mapped_poly % mod_poly
end

# Calculate q1(v), q2(v), q3(v), q4(v), q5(v)
q1 = φ(p1, g, f2)
q2 = φ(p2, g, f2)
q3 = φ(p3, g, f2)
q4 = φ(((p1 + p2 )* p3)%f1, g, f2)
q5 = ((φ(p1, g, f2) + φ(p2, g, f2)) * φ(p3, g, f2)) % f2

# print results
# println("q1(v) = ", q1)
# println("q2(v) = ", q2)
# println("q3(v) = ", q3)
# println("q4(v) = ", q4)
# println("q5(v) = ", q5)
#According to the polynomials of output
#and then manually assign the corresponding coefficient to the variable
A.Q8_5_a_ans_q1 = [1,0,1,1,1]
A.Q8_5_a_ans_q2 = [0,1,0,1]
A.Q8_5_a_ans_q3 = [0,0,0,1,1]
A.Q8_5_a_ans_q4 = [1,1]
A.Q8_5_a_ans_q5 = [0,0,0,0,1]


q1(v) = v^4 + v^3 + v^2 + 1
q2(v) = v^3 + v
q3(v) = v^4 + v^3
q4(v) = v + 1
q5(v) = v^4


5-element Vector{Int64}:
 0
 0
 0
 0
 1

In [ ]:
using Nemo

# Define finite field F2
F2 = GF(2)

# Define polynomial rings
R, u = polynomial_ring(F2, "u")
S, v = polynomial_ring(F2, "v")
#Define irreducible polynomials f1(u) and f2(v)
f1 = R(A.Q8_5_data_f1)
f2 = S(A.Q8_5_data_f2)

# elements on the domain
p1 = R(A.Q8_5_data_p1)
p2 = R(A.Q8_5_data_p2)
p3 = R(A.Q8_5_data_p3)
g = S(A.Q8_5_b_data_g2)

# Define mapping φ
function φ(poly, g, mod_poly)
    mapped_poly = S(0)
    for i in 0:degree(poly)
        mapped_poly += coeff(poly, i) * (g^i)
    end
    return mapped_poly % mod_poly
end

# Calculate q1(v), q2(v), q3(v), q4(v), q5(v)
q1 = φ(p1, g, f2)
q2 = φ(p2, g, f2)
q3 = φ(p3, g, f2)
q4 = φ(((p1 + p2) * p3)%f1, g, f2)
q5 = ((φ(p1, g, f2) + φ(p2, g, f2)) * φ(p3, g, f2)) % f2
# print results 
# println("q1(v) = ", q1)
# println("q2(v) = ", q2)
# println("q3(v) = ", q3)
# println("q4(v) = ", q4)
# println("q5(v) = ", q5)
#According to the polynomials of output
#and then manually assign the corresponding coefficient to the variable
A.Q8_5_b_ans_q1 = [0,1,0,1]
A.Q8_5_b_ans_q2 = [1,1,0,0,1]
A.Q8_5_b_ans_q3 = [0,0,0,1]
A.Q8_5_b_ans_q4 = [1,1,1,1,1]
A.Q8_5_b_ans_q5 = [1,1,1,1,1]

q1(v) = v^3 + v
q2(v) = v^4 + v + 1
q3(v) = v^3
q4(v) = v^4 + v^3 + v^2 + v + 1
q5(v) = v^4 + v^3 + v^2 + v + 1


5-element Vector{Int64}:
 1
 1
 1
 1
 1

# Q9.1
    Q9_1_data_r :: Int64
    Q9_1_a_ans_H :: Union{Missing, Matrix{Int64}}

    Q9_1_b_ans_G :: Union{Missing, Matrix{Int64}}

    Q9_1_c_data_p :: Float64
    Q9_1_c_ans_p_err :: Union{Missing, Float64}

    Q9_1_d_data_y_1 :: Vector{String}
    Q9_1_d_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_iii :: Union{Missing, Vector{Int64}}

    Q9_1_e_data_p :: Float64
    Q9_1_e_ans_p_err :: Union{Missing, Float64}

    Q9_1_f_data_y_2 :: Vector{String}
    Q9_1_f_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_f_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_f_ans_iii :: Union{Missing, Vector{Int64}}



In [212]:
mod.(transpose(A.Q9_1_b_ans_G)*A.Q9_1_f_ans_iii,2) == A.Q9_1_f_ans_ii


true

In [214]:
mod.(A.Q9_1_a_ans_H *A.Q9_1_f_ans_ii,2) 

6-element Vector{Int64}:
 0
 0
 0
 0
 0
 0

### 9.1


#### Question a,b

In [260]:
using LinearAlgebra
# function generate_hamming_matrix(r::Int)
#     num_columns = 2^r - 1
#     H = zeros(Int, r, num_columns)
    
#     for i in 1:num_columns
#         binary_representation = digits(i, base=2, pad=r)
#         H[:, i] .= binary_representation
#     end
    
#     return H
# end
function generate_hamming_matrix(r::Int)
    num_columns = 2^r - 1
    H = zeros(Int, r, num_columns)
    
    for i in 1:num_columns
        binary_representation = digits(i, base=2, pad=r)
        H[:, i] .= binary_representation
    end
    
    return H
end

r = 6
H = generate_hamming_matrix(r)

# specified column index
cols_to_extract = [1, 2, 4 ,8,16,32]

# The remaining columns form H2
H2 = H[:, setdiff(1:size(H, 2), cols_to_extract)]'

# Define the dimensions of G
rows, cols = 57, 63

# Construct G matrix
G = zeros(Int, rows, cols)

# Replace columns 1, 2, 4, 8, 16, 32
indices_to_replace = [1, 2, 4, 8, 16, 32]
for (i, col) in enumerate(indices_to_replace)
    G[:, col] = H2[:, i]
end

# Fill remaining columns with unit vectors
current_index = 1
for col in 1:cols
    if !(col in indices_to_replace)
        G[current_index, col] = 1
        current_index += 1
    end
end

A.Q9_1_a_ans_H = H;
A.Q9_1_b_ans_G = G


57×63 Matrix{Int64}:
 1  1  1  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  1  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  1  0  0  1  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  1  0  1  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  0  0  0  0  1  0  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  0  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  1  0  0  0  1  0  0  0  0  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  1  0  0  0  1  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 ⋮              ⋮              ⋮        ⋱              ⋮              ⋮     
 1  1  0  1  0  0  0  0  0  0  0  0  0     0  0  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  1  0  0  0  0  0     0

#### Qc


In [267]:
using Combinatorics

# Calculate the decoding error probability of a binary Hamming code
function decoding_error_probability(n, p_e)
    # Calculate P_err,1: the probability of an error occurring (i.e. 2 or more errors)）
    p_err = 0.0
    
    # Calculate error probabilities from 2 to n and accumulate them
    for k in 2:n
        p_err += binomial(n, k) * p_e^k * (1 - p_e)^(n - k)
    end
    
    return p_err
end

n = 63 
p_e = A.Q9_1_c_data_p  
A.Q9_1_c_ans_p_err = decoding_error_probability(n, p_e)

0.01968161379108231

### Qd
Q9_1_d_data_y_1 :: Vector{String}
    Q9_1_d_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_iii :: Union{Missing, Vector{Int64}}

In [269]:
# Example of a Hamming(7,4) parity-check matrix H
H = A.Q9_1_a_ans_H;

# Received word (replace with actual data from the file)
y1_string = A.Q9_1_d_data_y_1;   # Example: received word as a Vector{String}
# Step i: Convert received word to Vector{Int}
y1 = parse.(Int, y1_string)  # Convert the Vector{String} to Vector{Int}
A.Q9_1_d_ans_i = mod.((H * y1),2); # Make sure y1 is transposed to match the dimensions
## find the error location
err_i = 0;
for i in 1:size(H, 2)
    if all(A.Q9_1_d_ans_i .== H[:, i])
        err_i = i
        break
    end
end
y = y1  # Assume this is the received codeword
y[err_i] = 1 - y[err_i] 

## find the message
A.Q9_1_d_ans_ii = y;
c1 = A.Q9_1_d_ans_ii;
# Check digit position: 1, 2, 4, 8, 16, 32 (numbered starting from 1)
parity_positions = [1, 2, 4, 8, 16, 32]
# Extract message bits (remove check digits from codeword)
m1 = [c1[i] for i in 1:63 if !(i in parity_positions)]
A.Q9_1_d_ans_iii = m1;


#### Qe 



In [272]:
q = 2  
n = 63  
d_min = 3  
p_e = A.Q9_1_e_data_p  # Erase probability (set according to actual data)
k = 57  # Number of message bits

max_erasures = floor(Int, (d_min - 1) / 2)
prob_correct_decoding = 0.0
for i in 0:0
    prob_correct_decoding += binomial(n, i) * (p_e^i) * ((1 - p_e)^(n - i))
end
P_err_2 = 1 - prob_correct_decoding
A.Q9_1_e_ans_p_err = P_err_2;


#### Qf

In [273]:
# Step 1: Convert received word with '?' replaced by 0
# Assuming H is the parity-check matrix and y2_string is the received word (as a vector of strings)

H = A.Q9_1_a_ans_H  # Parity-check matrix
y2_string = A.Q9_1_f_data_y_2  # Received word (vector of strings)

# Replace '?' with 0 in the received word
y2 = parse.(Int, replace.(y2_string, "?" => "0"))

# Step 2: Find the syndrome vector s2
s2 = mod.(H * y2, 2)  # Syndrome calculation, modulo 2
# println("Syndrome vector s2: ", s2)
A.Q9_1_f_ans_i = s2
# Step 3: Find the transmitted codeword c2
# If syndrome is zero, received word is already a codeword
err_i = 0;
for i in 1:size(H, 2)
    if all(A.Q9_1_f_ans_i .== H[:, i])
        err_i = i
        break
    end
end
c2 = y2 
c2[err_i] = 1 - c2[err_i]  
A.Q9_1_f_ans_ii= c2;
# println("Transmitted codeword c2: ", c2)

# Step 4: Extract the message m2 from the transmitted codeword
# The message is the first 57 bits of the transmitted codeword (for [63, 57] code)
m2 = [c2[i] for i in 1:63 if !(i in parity_positions)]
A.Q9_1_f_ans_iii = m2;
# println("Message m2: ", m2)


57-element Vector{Int64}:
 0
 0
 1
 1
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 1
 0
 0
 0
 1
 1
 1

### 9.2


#### Q ab

In [274]:
function ham3(q, field_elements)
    num_cols = q + q^2 + 1 # The number of columns is q + q^2+1
    H = zeros(Int, 3, num_cols) 

    H[1, q +2:end] .= 1
    H[2, 2:q+1] .= 1
    #Second line: The first q column is 1, and subsequent ti is filled in blocks.
    for i in 1:q
        H[2, q + (i - 1) * q + 2 : q+1 + i * q] .= field_elements[i]
    end

    # The third line: the first q columns are t1 to tq, and the following are all possible permutations of (t1, t2, ..., tq)
    H[3, 2:q+1] .= field_elements
    for i in 1:q
        H[3, q + (i - 1) * q + 2 : q + i * q+1] .= field_elements
    end
    H[3,1] = 1;

    return H
end
q = 5
field_elements = [0,1, 2, 3, 4]
H3 = ham3(q, field_elements)
H = reverse(H3,dims=1)
A.Q9_2_a_ans_H = reverse(H3,dims=1)
#find the Matrix of G let G*H'= 0;
# specified column index
cols_to_extract = [1, 2, 7]
# The remaining columns form H2
H5 = H[:, setdiff(1:size(H, 2), cols_to_extract)]'
H5 = mod.(-1*H5,5)
rows, cols = 28, 31
# Construct G matrix
G2 = zeros(Int, rows, cols)
# Replace columns 1, 2, 7
indices_to_replace = [1,2,7]
for (i, col) in enumerate(indices_to_replace)
    G2[:, col] = H5[:, i]
end
# Fill remaining columns with unit vectors
current_index = 1
for col in 1:cols
    if !(col in indices_to_replace)
        G2[current_index, col] = 1
        current_index += 1
    end
end
A.Q9_2_b_ans_G = G2;

In [275]:
A.Q9_2_a_ans_H

3×31 Matrix{Int64}:
 1  0  1  2  3  4  0  1  2  3  4  0  1  …  3  4  0  1  2  3  4  0  1  2  3  4
 0  1  1  1  1  1  0  0  0  0  0  1  1     2  2  3  3  3  3  3  4  4  4  4  4
 0  0  0  0  0  0  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1

In [170]:
rank(mod.(A.Q9_2_b_ans_G*transpose(A.Q9_2_a_ans_H),5))

0

#### Q c


In [278]:
using Combinatorics

# Calculate the decoding error probability of a binary Hamming code
function decoding_error_probability(n, p_e)
    # Calculate P_err,1: the probability of an error occurring (i.e. 2 or more errors)）
    p_err = 0.0
    
    # Calculate error probabilities from 2 to n and accumulate them
    for k in 2:n
        p_err += binomial(n, k) * p_e^k * (1 - p_e)^(n - k)
    end
    
    return p_err
end

n = 31
p_e = A.Q9_2_c_data_p 
A.Q9_2_c_ans_p_err = decoding_error_probability(n, p_e)


0.0021570511266533255

#### Q d


In [279]:
H = A.Q9_2_a_ans_H;

# Received word (replace with actual data from the file)
y1_string = A.Q9_2_d_data_y_1;   # Example: received word as a Vector{String}
# Step i: Convert received word to Vector{Int}
y1 = parse.(Int, y1_string)  # Convert the Vector{String} to Vector{Int}
A.Q9_2_d_ans_i = mod.((H * y1),5); # Make sure y1 is transposed to match the dimensions
#find the c
C = zeros(Int,31)
C[28] = 2;
A.Q9_2_d_ans_ii = mod.(y1.-C,5);
## find the c1
c1 = A.Q9_2_d_ans_ii;
#Check digit position:1, 2, 7
parity_positions = [1, 2, 7]
# Extract message bits (remove check digits from codeword)
m1 = [c1[i] for i in 1:31 if !(i in parity_positions)]
A.Q9_2_d_ans_iii = m1;

In [280]:
mod.(transpose(A.Q9_2_b_ans_G)*m1,5) ==c1

true

In [281]:
mod.(H*A.Q9_2_d_ans_ii,5) 

3-element Vector{Int64}:
 0
 0
 0

### Q e
    Q9_2_e_data_p :: Float64
    Q9_2_e_ans_p_err :: Union{Missing, Float64}

In [282]:
q = 5  
n = 31  
d_min = 3  
p_e = A.Q9_2_e_data_p 
k = 28
max_erasures = floor(Int, (d_min - 1) / 2) 

# Calculate the probability of correct decoding when there are less than `max_erasures` erasures
prob_correct_decoding = 0.0
for i in 0:max_erasures
    prob_correct_decoding += binomial(n, i) * (p_e^i) * ((1 - p_e)^(n - i))
end

# Calculate error probability
P_err_2 = 1 - prob_correct_decoding
A.Q9_2_e_ans_p_err = P_err_2;


### Q f

In [283]:
# Step 1: Convert received word with '?' replaced by 0
# Assuming H is the parity-check matrix and y2_string is the received word (as a vector of strings)

H = A.Q9_2_a_ans_H;  # Parity-check matrix
y2_string = A.Q9_2_f_data_y_2  # Received word (vector of strings)

# Replace '?' with 0 in the received word
y2 = parse.(Int, replace.(y2_string, "?" => "0"))

# Step 2: Find the syndrome vector s2
s2 = mod.(H * y2, 5)  # Syndrome calculation, modulo 2
# println("Syndrome vector s2: ", s2)
A.Q9_2_f_ans_i = s2
# Step 3: Find the transmitted codeword c2
# If syndrome is zero, received word is already a codeword
# f = zeros(Int,31)
# f[7] = 2;
A.Q9_2_f_ans_ii = y2
# Step 4: Extract the message m2 from the transmitted codeword
m2 = [y2[i] for i in 1:31 if !(i in parity_positions)]
A.Q9_2_f_ans_iii = m2;
# println("Message m2: ", m2)

28-element Vector{Int64}:
 3
 1
 3
 2
 0
 2
 0
 3
 3
 0
 ⋮
 3
 2
 1
 0
 0
 0
 0
 0
 1

In [10]:
A

CourseWork_3(6007965, true, true, 2, 5, [[0], [1], [0, 1], [1, 1], [0, 0, 1], [1, 0, 1], [0, 1, 1], [1, 1, 1], [0, 0, 0, 1], [1, 0, 0, 1]  …  [0, 1, 1, 0, 1, 1], [1, 1, 1, 0, 1, 1], [0, 0, 0, 1, 1, 1], [1, 0, 0, 1, 1, 1], [0, 1, 0, 1, 1, 1], [1, 1, 0, 1, 1, 1], [0, 0, 1, 1, 1, 1], [1, 0, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]], 3, 4, [[0, 0, 0, 0, 1], [1, 0, 0, 0, 1], [2, 0, 0, 0, 1], [0, 1, 0, 0, 1], [1, 1, 0, 0, 1], [2, 1, 0, 0, 1], [0, 2, 0, 0, 1], [1, 2, 0, 0, 1], [2, 2, 0, 0, 1], [0, 0, 1, 0, 1]  …  [2, 2, 1, 2, 2], [0, 0, 2, 2, 2], [1, 0, 2, 2, 2], [2, 0, 2, 2, 2], [0, 1, 2, 2, 2], [1, 1, 2, 2, 2], [2, 1, 2, 2, 2], [0, 2, 2, 2, 2], [1, 2, 2, 2, 2], [2, 2, 2, 2, 2]], [1, 1, 0, 0, 1, 1, 1], true, true, false, [2, 2, 0, 1, 2], [2, 1, 2, 2], [2, 2, 1], [[2, 0, 0, 1]], [0, 2, 1, 2, 1, 2], [0, 1, 2, 2, 2], [2, 0, 2], [Int64[]], [2, 0, 0, 1, 2, 1], [2, 0, 1, 1, 2], [1, 1, 0, 1], [[0, 2], [0, 2, 0], [0, 2, 0, 0], [0, 2, 0, 0, 0], [1, 0, 1, 0, 1], [2, 1, 2, 0, 2]], [1, 1, 0, 

In [11]:
jldopen("Jiaqiang6007965StudentFile.jld2", "w") do file
   write(file, "CourseWork_3", A)
end